// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jitjvrxyxpnktslodfej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdGp2cnh5eHBua3RzbG9kZmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDA4MDEsImV4cCI6MjA2MTcxNjgwMX0.z0WCgp3cTLiB3IrhwUuz8Q4L7jRdNuoIMN2PtpGTLUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);